### ISSUE TITLE
FreeBSD: /usr/bin/ld: error: unable to find library -lfltk

### ISSUE THREAD

**Issue by eserte** [sanko/alien-fltk#2]
On some of my freebsd installations (seemingly the newer ones, freebsd 13 and 12) the test suite fails:
```
/usr/bin/ld: error: unable to find library -lfltk
cc: error: linker command failed with exit code 1 (use -v to see invocation)
error building /var/tmp/cpansmoker-1023/2018111711/alien_fltk_t0002_VrNE from /var/tmp/cpansmoker-1023/2018111711/alien_fltk_t0002_VrNE.o at /usr/local/lib/perl5/5.26/ExtUtils/CBuilder/Base.pm line 321.
# Looks like your test exited with 2 just after 1.
t/0002_exe.t .. 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/3 subtests 
```

**Comment by sanko** [comment]
The underlying FLTK 2.0 library is dead. When I inherited the project, it was based on the 2.0 branch which was abandoned upstream in 2011. They refuse to even distribute snapshots of the source which is why Alien::FLTK doesn't build. I planned to move to 1.3 (which was created after 2.0) but it was also dropped, then up to 3.0 in 2011-2012 which was also later dropped upstream, then 1.4 in 2016 which is still incomplete.

That's confusing, I know... Here's a commit timeline for the different branches: http://www.fltk.org/svn_monthly_commit_activity.svg

Every branch created and later abandoned is incompatible with the other branches because they redesign the entire API every single time.

See also:

- http://www.fltk.org/articles.php?L825
- http://www.fltk.org/software.php

**Comment by sanko** [comment]
The FLTK project moved to GitHub some time ago. I'll be using snapshots from here. 1.3.5 is current upstream. 1.4.x is still unstable.
